<a href="https://colab.research.google.com/github/harshsalvi1810/PythonProgramming/blob/main/Numpy_stat_L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [6]:
array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]).reshape(4,5)

array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
array[1:3,3:]

array([[ 8,  9],
       [13, 14]])

In [ ]:
'''
Stats:

1. Descriptive Stats : max,min,avg,count,kurtosis,skewness,std,variance etc...
2. Inferential Stats : Hypothesis Testing
'''
#-----------------------------------------------------------------------------
'''
Statistics consits of following steps..
step 1: collect data
step 2: organized data
step 3: summarized data
step 4: inferential stats
'''

In [ ]:
'''
Central tendency refers to the numerical value that represents the "center" or "typical" observations within a dataset.

central tendency are of three types
1.mean : avg value
2.median : central value
3.mode : most frequent occuring value

note:
a. mean and median use for numerical columns
b. mode generally use for categorical columns
'''

In [ ]:
'''
note 1:
when mean = median then such ditribution is called normally distributed data
this is also called symmetric distibution

note 2:
when mean > median then such ditribution is called positively skewed data
this is also called right skewed data

note 3:
when mean < median then such ditribution is called negatively skewed data
this is also called left skewed data
'''
array = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(array)
print(f"the mean value of array is",mean)
median = np.median(array)
print(f"the median value of array is",median)

In [9]:
array = np.array([100,400,700,300,200,100,800,900])

updated_araray = np.sort(array)

mean = np.mean(updated_araray)
print(f"the mean value of array is",mean)

median = np.median(updated_araray)
print(f"the median value of array is",median)
# Positive skew

[100 100 200 300 400 700 800 900]
the mean value of array is 437.5
the median value of array is 350.0


In [10]:
# Measure of dispersion
array = np.array([100,400,700,300,200,100,800,900])

max_value = np.max(array)
min_value = np.min(array)

range = max_value - min_value

print(range)

800


In [14]:
variance = np.var(array)
print(variance)

standard_deviation = np.std(array) # np.sqrt()
print(standard_deviation)

89843.75
299.739470207045


In [15]:
# calculation of IQR

Q1 = np.percentile(array,25)
Q3 = np.percentile(array,75)

IQR = Q3 - Q1
print(IQR)

550.0
