<a href="https://colab.research.google.com/github/harshsalvi1810/PythonProgramming/blob/main/Numpy_stat_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
'''
numpy:
- num --> numerical & py --> python
- It is a vectorised form of an array
- numpy is N-dimensional array
example:
1. a = np.array([2])  1D numpy array
2. b = np.array([[1,2,3]])  2D numpy array
3. c = np.array([[[1,2,3],[4,5,6]]])  3D numpy array
'''

'\nnumpy:\n- num --> numerical & py --> python\n- It is a vectorised form of an array\n- numpy is N-dimensional array\nexample:\n1. a = np.array([2])  1D numpy array\n2. b = np.array([[1,2,3]])  2D numpy array\n3. c = np.array([[[1,2,3],[4,5,6]]])  3D numpy array\n'

In [61]:
import numpy as np

array = np.array([1, 2, 3])

print(type(array))

<class 'numpy.ndarray'>


In [62]:
print(array.ndim)      # dimension of an array

1


In [63]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1.shape)

(2, 3)


In [64]:
array2 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(array1.shape)

(2, 3)


In [65]:
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(array2.T) # Transpose of a matrix : row to column

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [67]:
array2.flatten() #convert into 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
array2.sum(axis=0) # sum of columns

array([12, 15, 18])

In [69]:
array2.sum(axis=1) # sum of rows

array([ 6, 15, 24])

In [70]:
array2.max(),array2.min(),array2.mean()

(np.int64(9), np.int64(1), np.float64(5.0))

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.zeros(3)

array([0., 0., 0.])

In [73]:
np.ones(3)

array([1., 1., 1.])

In [74]:
array4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array4.shape

array4.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
array4.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [76]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

c = a + b

print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [77]:
a * 20

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

In [78]:
a > 1   # comparison

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [79]:
np.array([[1,2,3,4,5,6,7,8,9]]).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
a[:1,:1 ]

array([[1]])

In [81]:
# np.arrange(start,stop,step,datatype)
d = np.arange(1,36).reshape(7,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [82]:
d[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [83]:
e = np.arange(0,36,2).reshape(3,6)
e

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34]])

In [84]:
f = np.linspace(0,100,10,dtype = 'int')
f

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [85]:
# generating random nummber
np.random.seed(0)  #lock the random values
np.random.rand(3,3) # generate

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [86]:
np.random.randint(low = 0,high = 2,size = (3,3)) # generate


array([[0, 1, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [87]:
r = np.random.randint(low = 0,high = 2,size = (3,3))

In [88]:
r.ravel() # convert into 1D more efficient than flatten

array([1, 1, 0, 1, 0, 1, 0, 1, 1])

In [90]:
'''
1. when mean = median then the distribution is symmetric/(normally distributed or no skewed distribution).
2. when mean > median then the distribution is positively skewed.
3. when mean < median then the distribution is negatively skewed.
'''
np.median(a),np.mean(a),np.std(a),np.var(a),np.min(a),np.max(a),np.sum(a)

(np.float64(5.0),
 np.float64(5.0),
 np.float64(2.581988897471611),
 np.float64(6.666666666666667),
 np.int64(1),
 np.int64(9),
 np.int64(45))